<?php
date_default_timezone_set('America/Sao_paulo');
define('DB_HOSTNAME','localhost');
define('DB_USERNAME','db_user');
define('DB_PASSWORD','db_pass');
define('DB_DATABASE','useacabeca'); 
define('DB_PREFIX',null);
define('DB_CHARSET','utf8');
?>
